//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyMVVM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TinyMVVM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piper
        ///Kylie
        ///April
        ///Cassandra
        ///Vivien
        ///Bell
        ///Yen
        ///Nelle
        ///Suki
        ///Mollie
        ///Destiny
        ///Faith
        ///Cheryl
        ///Colette
        ///Zephr
        ///Celeste
        ///Aretha
        ///Emily
        ///Desiree
        ///Fatima
        ///Quon
        ///Jennifer
        ///Nola
        ///Brooke
        ///Galena
        ///Kirestin
        ///Kameko
        ///Eve
        ///Rhiannon
        ///Elaine
        ///Elizabeth
        ///Lacey
        ///Rhiannon
        ///Gretchen
        ///Neve
        ///Paloma
        ///Jael
        ///Miranda
        ///Jada
        ///Freya
        ///Halla
        ///Minerva
        ///Lucy
        ///Kirestin
        ///Skyler
        ///Lillian
        ///Nayda
        ///Veronica
        ///Shannon
        ///Venus
        ///Dana
        ///Maggie
        ///Idola
        ///Ursula
        ///Orli
        ///Morgan
        ///Jenna
        ///Colleen
        ///Wilma
        ///Dawn
        ///Josephine
        ///Dai
        ///Rachel
        ///Dora
        ///Lani
        ///Jordan
        ///Yoshi
        ///Xantha
        ///Brooke
        ///Inga
        ///Emerald
        ///Josephine
        ///Ann
        ///Shay
        ///Yuri
        ///Vanna
        ///Jael
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name
        ///Kasimir
        ///Ali
        ///Hunter
        ///Hop
        ///Thomas
        ///Carson
        ///Kasimir
        ///Scott
        ///Uriah
        ///Victor
        ///Zahir
        ///Kennan
        ///Gareth
        ///Tyler
        ///Paul
        ///Kenneth
        ///Raja
        ///Dominic
        ///Matthew
        ///Aristotle
        ///Graham
        ///Chaim
        ///Josiah
        ///Tyler
        ///Solomon
        ///Graiden
        ///Kermit
        ///Hop
        ///Burton
        ///Keith
        ///Kasimir
        ///Neil
        ///Lars
        ///Alexander
        ///Carl
        ///Jarrod
        ///Clarke
        ///Oleg
        ///Finn
        ///Bruno
        ///Matthew
        ///Ezekiel
        ///Nissim
        ///Arden
        ///David
        ///Ignatius
        ///Lucian
        ///Arden
        ///Prescott
        ///Elijah
        ///Branden
        ///Carter
        ///Jared
        ///Mannix
        ///Benjamin
        ///Fulton
        ///Arthur
        ///Micah
        ///Ryan
        ///Coby
        ///Dante
        ///Giacomo
        ///Upton
        ///Stone
        ///Harlan
        ///Berk
        ///Garrett
        ///Lucius
        ///Ryan
        ///Oren
        ///Quinn
        ///Jasper
        ///Barry
        ///Jared
        ///Keefe
        ///Ferris
        ///Yul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name
        ///Giles
        ///Cummings
        ///Kennedy
        ///Mullins
        ///Hawkins
        ///Downs
        ///Ashley
        ///Blake
        ///Love
        ///Coffey
        ///Dillon
        ///Maddox
        ///Battle
        ///Sheppard
        ///Hernandez
        ///Le
        ///Woods
        ///Odom
        ///Dixon
        ///Pollard
        ///Mcintosh
        ///Solis
        ///Rowland
        ///Doyle
        ///Chase
        ///Vargas
        ///Franklin
        ///Mcclain
        ///Dunlap
        ///Hickman
        ///Alvarado
        ///Mcguire
        ///Montoya
        ///Knapp
        ///Doyle
        ///Ballard
        ///Reeves
        ///Espinoza
        ///Bryan
        ///Foster
        ///Hughes
        ///Gonzalez
        ///Solis
        ///Kline
        ///Combs
        ///Espinoza
        ///Baldwin
        ///Clements
        ///Weber
        ///Evans
        ///Tucker
        ///Lynn
        ///Calhoun
        ///Patrick
        ///Rush
        ///Ford
        ///Mills
        ///Buchanan
        ///Stuart
        ///Summers
        ///Leonard
        ///Terrell
        ///Joseph
        ///Chapman
        ///Head
        ///Porter
        ///Cooke
        ///Chan
        ///Aguilar
        ///Franks
        ///Hutchinson
        ///H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Surnames {
            get {
                return ResourceManager.GetString("Surnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lazy
        ///Dog
        ///Jumped.
        /// </summary>
        internal static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
    }
}
