//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyMVVM.VSIntegration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TinyMVVM.VSIntegration.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;#@ template language=&quot;C#&quot; #&gt;
        ///&lt;#@ assembly name=&quot;System.Core.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.Linq&quot; #&gt;
        ///&lt;#@ assembly name=&quot;$(TinyMVVMDir)\TinyMVVM.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.DSL.TextParser&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.SemanticModel.MVVM&quot; #&gt;
        ///&lt;#
        ///	var mvvmFile = @&quot;$(MvvmFilePath)&quot;;
        ///	var parser = new Parser();
        ///	var modelSpec = parser.Parse(Code.FromFile(mvvmFile));
        ///	var viewModel = modelSpec.ViewModels.SingleOrDefault(vm =&gt; vm.Name == &quot;$(ViewModel)&quot;);
        ///#&gt;
        ///
        ///&lt;# if (viewModel != nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodeBehindViewModelTemplateContent {
            get {
                return ResourceManager.GetString("CodeBehindViewModelTemplateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;#@ template language=&quot;C#&quot; #&gt;
        ///&lt;#@ assembly name=&quot;System.Core.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.Linq&quot; #&gt;
        ///&lt;#@ assembly name=&quot;$(TinyMVVMDir)\TinyMVVM.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.DSL.TextParser&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.SemanticModel.MVVM&quot; #&gt;
        ///&lt;#
        ///	var mvvmFile = @&quot;$(MvvmFilePath)&quot;;
        ///	var parser = new Parser();
        ///	var modelSpec = parser.Parse(Code.FromFile(mvvmFile));
        ///	var viewModel = modelSpec.ViewModels.SingleOrDefault(vm =&gt; vm.Name == &quot;$(ViewModel)&quot;);
        ///#&gt;
        ///
        ///&lt;# if (viewModel != nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ControllerTemplateContent {
            get {
                return ResourceManager.GetString("ControllerTemplateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;#@ template language=&quot;C#&quot; #&gt;
        ///&lt;#@ assembly name=&quot;System.Core.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.Linq&quot; #&gt;
        ///&lt;#@ assembly name=&quot;$(TinyMVVMDir)\TinyMVVM.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.DSL.TextParser&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.SemanticModel.MVVM&quot; #&gt;
        ///&lt;#
        ///	var mvvmFile = @&quot;$(MvvmFilePath)&quot;;
        ///	var parser = new Parser();
        ///	var modelSpec = parser.Parse(Code.FromFile(mvvmFile));
        ///	var viewModel = modelSpec.ViewModels.SingleOrDefault(vm =&gt; vm.Name == &quot;$(ViewModel)&quot;);
        ///#&gt;
        ///
        ///&lt;# if (viewModel != nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PartialViewModelTemplateContent {
            get {
                return ResourceManager.GetString("PartialViewModelTemplateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;#@ template language=&quot;C#&quot; #&gt;
        ///&lt;#@ assembly name=&quot;System.Core.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.Linq&quot; #&gt;
        ///&lt;#@ assembly name=&quot;$(TinyMVVMDir)\TinyMVVM.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.DSL.TextParser&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.SemanticModel.MVVM&quot; #&gt;
        ///&lt;#
        ///	var mvvmFile = @&quot;$(MvvmFilePath)&quot;;
        ///	var parser = new Parser();
        ///	var modelSpec = parser.Parse(Code.FromFile(mvvmFile));
        ///	var viewModel = modelSpec.ViewModels.SingleOrDefault(vm =&gt; vm.Name == &quot;$(ViewModel)&quot;);
        ///#&gt;
        ///&lt;# if (viewModel != null [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestScenarioTemplateContent {
            get {
                return ResourceManager.GetString("TestScenarioTemplateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;#@ template language=&quot;C#&quot; #&gt;
        ///&lt;#@ assembly name=&quot;System.Core.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.Linq&quot; #&gt;
        ///&lt;#@ assembly name=&quot;$(TinyMVVMDir)\TinyMVVM.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.DSL.TextParser&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.SemanticModel.MVVM&quot; #&gt;
        ///&lt;#
        ///	var mvvmFile = @&quot;$(MvvmFilePath)&quot;;
        ///	var parser = new Parser();
        ///	var modelSpec = parser.Parse(Code.FromFile(mvvmFile));
        ///	var viewModel = modelSpec.ViewModels.SingleOrDefault(vm =&gt; vm.Name == &quot;$(ViewModel)&quot;);
        ///#&gt;
        ///&lt;# if (viewModel != null [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnitTestTemplateContent {
            get {
                return ResourceManager.GetString("UnitTestTemplateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;#@ template language=&quot;C#&quot; #&gt;
        ///&lt;#@ assembly name=&quot;System.Core.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.Linq&quot; #&gt;
        ///&lt;#@ assembly name=&quot;$(TinyMVVMDir)\TinyMVVM.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.DSL.TextParser&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.SemanticModel.MVVM&quot; #&gt;
        ///&lt;#
        ///	var mvvmFile = @&quot;$(MvvmFilePath)&quot;;
        ///	var parser = new Parser();
        ///	var modelSpec = parser.Parse(Code.FromFile(mvvmFile));
        ///	var viewModel = modelSpec.ViewModels.SingleOrDefault(vm =&gt; vm.Name == &quot;$(ViewModel)&quot;);
        ///#&gt;
        ///
        ///&lt;# if (viewModel != nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewCodeBehindTemplateContent {
            get {
                return ResourceManager.GetString("ViewCodeBehindTemplateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;#@ template language=&quot;C#&quot; #&gt;
        ///&lt;#@ assembly name=&quot;System.Core.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.Linq&quot; #&gt;
        ///&lt;#@ assembly name=&quot;$(TinyMVVMDir)\TinyMVVM.dll&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.DSL.TextParser&quot; #&gt;
        ///&lt;#@ import namespace=&quot;TinyMVVM.SemanticModel.MVVM&quot; #&gt;
        ///&lt;#
        ///	var mvvmFile = @&quot;$(MvvmFilePath)&quot;;
        ///	var parser = new Parser();
        ///	var modelSpec = parser.Parse(Code.FromFile(mvvmFile));
        ///	var viewModel = modelSpec.ViewModels.SingleOrDefault(vm =&gt; vm.Name == &quot;$(ViewModel)&quot;);
        ///#&gt;
        ///
        ///&lt;# if (viewModel != nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewTemplateContent {
            get {
                return ResourceManager.GetString("ViewTemplateContent", resourceCulture);
            }
        }
    }
}
